Update to open-vm-tools 9.0.0

diff --git a/scripts/linux/network b/scripts/linux/network
--- a/scripts/linux/network
+++ b/scripts/linux/network
@@ -47,34 +47,57 @@ echo
 #
 
 find_networking_script() {
-    local script="error"
-    for dir in "/etc/init.d" "/sbin/init.d" "/etc" "/etc/rc.d" ; do
-        if [ -d "$dir/rc0.d" ] &&
-	    [ -d "$dir/rc1.d" ] &&
-	    [ -d "$dir/rc2.d" ] &&
-	    [ -d "$dir/rc3.d" ] &&
-	    [ -d "$dir/rc4.d" ] &&
-	    [ -d "$dir/rc5.d" ] &&
-	    [ -d "$dir/rc6.d" ]; then
+   local script="error"
+   for dir in "/etc/init.d" "/sbin/init.d" "/etc" "/etc/rc.d" ; do
+      if [ -d "$dir/rc0.d" ] &&
+         [ -d "$dir/rc1.d" ] &&
+         [ -d "$dir/rc2.d" ] &&
+         [ -d "$dir/rc3.d" ] &&
+         [ -d "$dir/rc4.d" ] &&
+         [ -d "$dir/rc5.d" ] &&
+         [ -d "$dir/rc6.d" ]; then
 
-	    # Now find the appropriate networking script.
-	    if [ -d "$dir/init.d" ]; then
-		if [ -x "$dir/init.d/network" ]; then
-		    script="$dir/init.d/network"
-		elif [ -x "$dir/init.d/networking" ]; then
-		    script="$dir/init.d/networking"
-		fi
-	    else
-		if [ -x "$dir/network" ]; then
-		    script="$dir/network"
-		elif [ -x "$dir/networking" ]; then
-		    script="$dir/networking"
-		fi
-	    fi
-        fi
-    done
+         # Now find the appropriate networking script.
+         if [ -d "$dir/init.d" ]; then
+            if [ -x "$dir/init.d/network" ]; then
+               script="$dir/init.d/network"
+            elif [ -x "$dir/init.d/networking" ]; then
+               script="$dir/init.d/networking"
+            fi
+         else
+            if [ -x "$dir/network" ]; then
+               script="$dir/network"
+            elif [ -x "$dir/networking" ]; then
+               script="$dir/networking"
+            fi
+         fi
+      fi
+   done
 
-    echo "$script"
+   echo "$script"
+}
+
+
+#
+# run_network_script --
+#
+# Finds out how to run the system's script used to control networking, and
+# runs it with the given argument (which should be one of the usual SysV
+# init script arguments).
+#
+run_network_script()
+{
+   script=`find_networking_script`
+   [ "$script" != "error" ] || Panic "Cannot find system networking script."
+
+   # Using SysV "service" if it exists, otherwise fall back to run the script directly
+   service=`which service 2>/dev/null`
+   if [ $? = 0 -a -n "$service" ]; then
+      serviceName=`basename "$script"`
+      "$service" "$serviceName" "$1"
+   else
+      "$script" "$1"
+   fi
 }
 
 
@@ -145,19 +168,38 @@ rescue_NIC() {
 #    None.
 #
 
-TranquilizeNetworkManager() {
+TranquilizeNetworkManager()
+{
    # `which' may be a bit noisy, so we'll shush it.
    dbusSend=`which dbus-send 2>/dev/null`
-   if [ $? -eq 0 ]; then
-      # NetworkManager 0.6
-      $dbusSend --system --dest=org.freedesktop.NetworkManager          \
-         /org/freedesktop/NetworkManager                                \
-         org.freedesktop.NetworkManager.sleep
+   rc=$?
+   if [ $rc = 0 ]; then
+      # NetworkManager 0.8.0
+      $dbusSend --system --print-reply          \
+         --dest=org.freedesktop.NetworkManager  \
+         /org/freedesktop/NetworkManager        \
+         org.freedesktop.NetworkManager.Enable boolean:false
+      rc=$?
+      if [ $rc = 0 ]; then
+         return $rc
+      fi
       # NetworkManager 0.7.0
-      $dbusSend --system --dest=org.freedesktop.NetworkManager          \
-         /org/freedesktop/NetworkManager                                \
+      $dbusSend --system --print-reply          \
+         --dest=org.freedesktop.NetworkManager  \
+         /org/freedesktop/NetworkManager        \
          org.freedesktop.NetworkManager.Sleep boolean:true
+      rc=$?
+      if [ $rc = 0 ]; then
+         return $rc
+      fi
+      # NetworkManager 0.6
+      $dbusSend --system --print-reply          \
+         --dest=org.freedesktop.NetworkManager  \
+         /org/freedesktop/NetworkManager        \
+         org.freedesktop.NetworkManager.sleep
+      rc=$?
    fi
+   return $rc
 }
 
 
@@ -175,19 +217,38 @@ TranquilizeNetworkManager() {
 #    None.
 #
 
-WakeNetworkManager() {
+WakeNetworkManager()
+{
    # `which' may be a bit noisy, so we'll shush it.
    dbusSend=`which dbus-send 2>/dev/null`
-   if [ $? -eq 0 ]; then
-      # NetworkManager 0.6
-      $dbusSend --system --dest=org.freedesktop.NetworkManager          \
-         /org/freedesktop/NetworkManager                                \
-         org.freedesktop.NetworkManager.wake
+   rc=$?
+   if [ $rc = 0 ]; then
+      # NetworkManager 0.8.0
+      $dbusSend --system --print-reply          \
+         --dest=org.freedesktop.NetworkManager  \
+         /org/freedesktop/NetworkManager        \
+         org.freedesktop.NetworkManager.Enable boolean:true
+      rc=$?
+      if [ $rc = 0 ]; then
+         return $rc
+      fi
       # NetworkManager 0.7.0
-      $dbusSend --system --dest=org.freedesktop.NetworkManager          \
-         /org/freedesktop/NetworkManager                                \
+      $dbusSend --system --print-reply          \
+         --dest=org.freedesktop.NetworkManager  \
+         /org/freedesktop/NetworkManager        \
          org.freedesktop.NetworkManager.Sleep boolean:false
+      rc=$?
+      if [ $rc = 0 ]; then
+         return $rc
+      fi
+      # NetworkManager 0.6
+      $dbusSend --system --print-reply          \
+         --dest=org.freedesktop.NetworkManager  \
+         /org/freedesktop/NetworkManager        \
+         org.freedesktop.NetworkManager.wake
+      rc=$?
    fi
+   return $rc
 }
 
 
@@ -205,9 +266,6 @@ main() {
    exitCode=0
    activeList=/var/run/vmware-active-nics
 
-   networkScript=`find_networking_script`
-   [ "$networkScript" != "error" ] || Panic "Cannot find system networking script."
-
    # XXX Are these really necessary?  If so, we should have seen customer
    # complaints by now.
    which ifup >/dev/null 2>&1      || Panic "ifup not in search path."
@@ -218,30 +276,40 @@ main() {
          rm -f $activeList
          ;;
       suspend-vm)
-         save_active_NIC_list
-         "$networkScript" stop
          TranquilizeNetworkManager
+         exitCode=$?
+         if [ $exitCode != 0 ]; then
+            save_active_NIC_list
+            run_network_script stop
+            exitCode=$?
+         fi
          ;;
       resume-vm)
-         # According to hfu, "/etc/init.d/networking restart" on Debian 5.0
-         # may bring down ethernet interfaces tagged as "allow-hotplug" without
-         # bringing them back up.
-         #
-         # This is especially a problem when reverting to a live, running
-         # VM snapshot where an active NIC list hadn't yet been generated,
-         # resulting in sudden loss of an otherwise operational NIC.
-         #
-         # So, if the active list doesn't exist, assume we're coming back to
-         # a live snapshot and capture the current active list now for
-         # rescue later.
-         if [ ! -s $activeList ]; then
-            save_active_NIC_list
-         fi
          WakeNetworkManager
-         # XXX Do we really want restart or is start sufficient?  Like, would
-         # using start avoid the problem mentioned above?
-         "$networkScript" restart
-         rescue_NIC
+         exitCode=$?
+         if [ $exitCode != 0 ]; then
+            # According to hfu, "/etc/init.d/networking restart" on Debian 5.0
+            # may bring down ethernet interfaces tagged as "allow-hotplug" without
+            # bringing them back up.
+            #
+            # This is especially a problem when reverting to a live, running
+            # VM snapshot where an active NIC list hadn't yet been generated,
+            # resulting in sudden loss of an otherwise operational NIC.
+            #
+            # So, if the active list doesn't exist, assume we're coming back to
+            # a live snapshot and capture the current active list now for
+            # rescue later.
+            if [ ! -s $activeList ]; then
+               save_active_NIC_list
+            fi
+
+            # We shall use start not restart here. Otherwise we may not be able
+            # to bring back active list on distros like sles11sp2
+            # -- PR 816791
+            run_network_script start
+            rescue_NIC
+            exitCode=$?
+         fi
          ;;
       *) ;;
    esac
